const express = require('express');
const {airplaneController} = require('../../controllers');
const router = express.Router();
const airplaneMiddlewares=require("../../middleware/airplane-middleware");
router.post('/',airplaneMiddlewares.validateCreateAirplane,airplaneController.createAirplane);
router.get('/',airplaneController.getAirplanes);
router.get('/:id',airplaneController.getAirplane);
router.delete('/:id',airplaneController.destroyAirplane);
router.put('/:id',airplaneController.updateAirplane);
module.exports = router;